esphome:
  name: wyze-outdoor
  friendly_name: 'wyzeOutdoor'
  project:
    name: 'https://github.com/Photonicsguy/ESPHome-projects/wyzeOutdoor/'
    version: "2.1"
  name_add_mac_suffix: true
esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf
    version: recommended
logger:
  level: INFO
  baud_rate: 0
api:
#  encryption:
#    key: !secret enc_key
ota:
  platform: esphome
  password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  min_auth_mode: WPA2
  ap:
   ssid: "wyzeOutdoor Fallback"
   password: !secret fallback_hotspot_pass
captive_portal:
dashboard_import:
  package_import_url: github://Photonicsguy/ESPhome-projects/wyzeOutdoor/wyzeOutdoor.yaml@main
  import_full_config: True
time:
  - platform: homeassistant
    id: hass_time
preferences:
  flash_write_interval: 90min

#esp32_ble_tracker:
#  scan_parameters:
#    active: true
bluetooth_proxy:
  active: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
      entity_category: "diagnostic"
      disabled_by_default: true
substitutions:
  # Calibration
  voltage_div: 684.00
  current_res: 0.002400
  current_multiply: 1.7600

#status_led:
#  pin:
#    number: GPIO5
#    inverted: true
#    ignore_strapping_warning: true

button:
  - platform: restart
    name: Restart
    disabled_by_default: true

switch:
  - platform: gpio
    name: Relay1
    pin:
      number: GPIO15
      inverted: false
      ignore_strapping_warning: true
    id: relay1
    on_turn_on:
      - light.turn_on: relay1_led
    on_turn_off:
      - light.turn_off: relay1_led
  - platform: gpio
    name: Relay2
    pin:
      number: GPIO32
      inverted: false
    id: relay2
    on_turn_on:
      - light.turn_on: relay2_led
    on_turn_off:
      - light.turn_off: relay2_led
  - platform: template
    name: "Local control"
    id: localControl
    optimistic: True
    restore_mode: RESTORE_DEFAULT_OFF


output:
  - platform: gpio
    pin: GPIO19
    inverted: True
    id: relay1_led_gpio
  - platform: gpio
    pin: GPIO16
    inverted: True
    id: relay2_led_gpio

light:
  - platform: status_led
    name: "Status"
    entity_category: "diagnostic"
    icon: mdi:alarm-light
    pin:
      number: GPIO05
      inverted: true

  - platform: binary
    name: "Relay1 LED"
    id: relay1_led
    internal: true
    output: relay1_led_gpio
  - platform: binary
    name: "Relay2 LED"
    id: relay2_led
    internal: true
    output: relay2_led_gpio

sensor:
  - platform: wifi_signal
    name: "RSSI"
    entity_category: "diagnostic"
    id: rssi_db
    update_interval: 5min
    filters:
      - delta: 2.0
  - platform: uptime
    entity_category: "diagnostic"
    type: timestamp
    name: Uptime
  - platform: internal_temperature
    name: "Internal Temperature"
    entity_category: "diagnostic"
    disabled_by_default: true
    update_interval: 300s
  - platform: adc
    pin: GPIO34
    name: "LUX"
    id: lux_sensor
    device_class: illuminance
    unit_of_measurement: lx
    attenuation: 12db
  - platform: hlw8012
    sel_pin:
      number: GPIO25
      inverted: true
    cf_pin: GPIO27
    cf1_pin: GPIO26
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    change_mode_every: 3
    update_interval: 3s
    current:
      name: "Current"
      unit_of_measurement: A
      accuracy_decimals: 2
      filters:
        - multiply: ${current_multiply}
        - round: 2
    voltage:
      name: "Voltage"
      unit_of_measurement: V
      accuracy_decimals: 1
      filters:
        - round: 1
    power:
      name: "Power"
      id: my_power
      unit_of_measurement: W
      accuracy_decimals: 0
      filters:
        - round: 1
    energy:
      name: "Energy"
  - platform: template
    name: "Power Factor"
    state_class: "measurement" 
    lambda: |-
      if(id(current).state<0.0001)
      return 1.0;
      else return id(power).state / (id(voltage).state * id(current).state);
    accuracy_decimals: 2
    filters:
      - round: 2
      - clamp:
          min_value: 0
          max_value: 1
          ignore_out_of_range: false


binary_sensor:
#  - platform: template
#    id: localControlSensor
#    internal: true
  - platform: gpio
    disabled_by_default: true
    pin:
      number: GPIO18
      mode: INPUT_PULLDOWN
      inverted: False
    name: Button1
    on_press:
       if:
        condition:
          switch.is_on: localControl
        then:
          - switch.toggle: relay1
  - platform: gpio
    disabled_by_default: true
    pin:
      number: GPIO17
      mode: INPUT_PULLDOWN
      inverted: False
    name: Button2
    on_press:
      if:
        condition:
          switch.is_on: localControl
        then:
          - switch.toggle: relay2
  - platform: template
    name: Daylight
    device_class: light
    lambda: |-
        // the sensor reads 3.1 volts if there is light and 0.5 if there is not light not much in between
        if (id(lux_sensor).state > 2) {
          // there is daylight outside.
          return true;
        } else {
          // there is no daylight outside (e.g. it is dark).
          return false;
        }

