esphome:
  name: growlight
  friendly_name: GrowLight
  project:
    name: "https://github.com/Photonicsguy/ESPHome-projects/growLight/"
    version: '1.3'
  name_add_mac_suffix: true
esp8266:
  board: esp01_1m
logger:
  level: INFO
  baud_rate: 0
api:
#  encryption:
#    key: !secret enc_key
#  reboot_timeout: 6h
ota:
  - platform: esphome
    password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  min_auth_mode: WPA2
  ap:
   ssid: "Growlight Fallback"
   password: !secret fallback_hotspot_pass
captive_portal:

dashboard_import:
  package_import_url: github://Photonicsguy/ESPhome-projects/growLight/growLight.yaml@main
  import_full_config: False
  
time:
  - platform: homeassistant
    id: hass_time
    on_time_sync:
      then:
        - script.execute: autoScript

sun:
  latitude: !secret latitude
  longitude: !secret longitude
  on_sunrise:
    - then:
        - script.execute: autoScript
  on_sunset:
    - then:
        - script.execute: autoScript

#text_sensor:
#  - platform: sun
#    name: Sun Next Sunrise
#    type: sunrise
#    entity_category: "diagnostic"
#  - platform: sun
#    name: Sun Next Sunset
#    type: sunset
#    entity_category: "diagnostic"
sensor:
  - platform: uptime
    type: timestamp
    name: Uptime
    entity_category: "diagnostic"
#  - platform: sun
#    name: Sun Elevation
#    type: elevation
#    icon: mdi:sun-angle
switch:
  - platform: gpio
    name: "Light"
    pin: GPIO0
    id: relay
    inverted: True
    icon: mdi:desk-lamp
    restore_mode: ALWAYS_OFF
  - platform: template
    name: "Automatic mode"
    id: automated
    icon: mdi:sun-clock
    entity_category: "config"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    on_state:
      - if:
          condition:
            lambda: 'return x;'
          then:
            - script.execute: autoScript

#button:
#  - platform: restart
#    name: "Restart"

script:
  - id: autoScript
    then:
      - if:
          condition:
            - switch.is_on: automated
          then:
            - if:
                condition:
                  - sun.is_above_horizon:
                then:
                  - logger.log: "Sun is above horizon."
                  - switch.turn_on: relay
                else:
                  - logger.log: "Sun is below horizon."
                  - switch.turn_off: relay
