esphome:
  name: esp32
  friendly_name: ESP32
  project:
    name: 'https://github.com/Photonicsguy/ESPHome-projects'
    version: "0.1"
  name_add_mac_suffix: true

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

logger:
  level: INFO
api:
ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  min_auth_mode: WPA2
  ap:
   ssid: "blankESP32 Fallback"
   password: '12345678'
captive_portal:

dashboard_import:
  package_import_url: github://Photonicsguy/ESPhome-projects/tpl/blankESP32.yaml@main
  import_full_config: True

time:
  - platform: homeassistant
    id: hass_time
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
      entity_category: "diagnostic"
      disabled_by_default: true
button:
  - platform: restart
    id: btnRestart
    name: Reboot
sensor:
  - platform: wifi_signal
    name: "RSSI"
    entity_category: "diagnostic"
    disabled_by_default: true
    id: rssi_db
    filters:
      - delta: 2
      - throttle_average: 900s
  - platform: uptime
    entity_category: "diagnostic"
    type: timestamp
    name: Uptime
  - platform: internal_temperature
    name: "Internal Temperature"
    entity_category: "diagnostic"
